language: ruby
rvm:
  - 2.6.3
script:
  - gem install jekyll jekyll-paginate jekyll-sitemap
  - jekyll build
after_success:
  - git clone https://github.com/mritd/mritd.me.git
  - cd mritd.me && rm -rf * && cp -r ../_site/* .
  - git config user.name "mritd"
  - git config user.email "mritd@linux.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$JEKYLL_GITHUB_TOKEN@github.com/mritd/mritd.me.git master
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
